version: '3.8'

services:
  schedule-university-main:
    image: schedule-university-main
    build: .
    container_name: schedule-university-main-container
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: schedule_university_auth
      DB_USER: abuser
      DB_PASSWORD: abuser
      SPRING_PROFILES_ACTIVE: prod
      LOGGING_LEVE: INFO
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:17
    container_name: schedule_university_DB
    environment:
      POSTGRES_USER: abuser
      POSTGRES_PASSWORD: abuser
      POSTGRES_DB: schedule_university
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana-enterprise:11.3.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    restart: always
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  mongo:
    image: mongo:8.0.3
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: abuser
      MONGO_INITDB_ROOT_PASSWORD: abuser
      MONGO_INITDB_DATABASE: schedule_university

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: abuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: abuser
      ME_CONFIG_MONGODB_URL: mongodb://abuser:abuser@mongo:27017/
      ME_CONFIG_BASICAUTH: false



volumes:
  postgres_data:
  grafana_data:
  prometheus_data:
  mongo_data:
