version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: schedule_university_DB
    environment:
      POSTGRES_USER: abuser
      POSTGRES_PASSWORD: abuser
      POSTGRES_DB: schedule_university
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana-enterprise:11.3.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    restart: always
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: abuser
      MONGO_INITDB_ROOT_PASSWORD: abuser
      MONGO_INITDB_DATABASE: schedule-university
    volumes:
      - mongo_data:/data/db
      - ./src/test/resources/mongo:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

volumes:
  postgres_data:
  grafana_data:
  prometheus_data:
  mongo_data:
