global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'schedule-university-main'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host:8191']

  - job_name: 'scheduler-parser'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host:8091']